# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa7abee752cba3f57e510c97a2adad1730c2c938e2ce2ccc3360008f8422e36fb60a6e67efd8d3536e432024cd39a759d3a6f1f5e5e6b2d8db3f4c54cbf2d1f7

test:
  secret_key_base: be5ef325000d1d4ef393ee6f122115a911c60291cecbeb07e36dd2d9c2e17a3d29a4d4f8811dc9ba15f61523c97379e23ce76ea09a3d73f15ff62c58670f0518

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
